apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail-config
  namespace: monitoring
data:
  promtail.yaml: |
    server:
      http_listen_port: 3101
      grpc_listen_port: 0

    positions:
      filename: /tmp/positions.yaml

    clients:
      - url: http://10.148.15.213:3100/loki/api/v1/push  # <== IP VM monitoring (Loki)

    scrape_configs:
      # ================================
      # 1️⃣ System Logs (syslog, auth, kernel, dsb.)
      # ================================
      - job_name: system-logs
        static_configs:
          - targets:
              - localhost
            labels:
              job: system-logs
              host: ${HOSTNAME}
              __path__: /var/log/{syslog,auth.log,kern.log}

      # ================================
      # 2️⃣ Container Logs (semua container Docker/K8s)
      # ================================
      - job_name: container-logs
        static_configs:
          - targets:
              - localhost
            labels:
              host: ${HOSTNAME}
              __path__: /var/log/containers/*.log
        relabel_configs:
          - target_label: job
            replacement: container-logs

      # ================================
      # 3️⃣ Pod Logs (untuk log di /var/log/pods, termasuk wandoor-backend)
      # ================================
      - job_name: pod-logs
        static_configs:
          - targets:
              - localhost
            labels:
              host: ${HOSTNAME}
              __path__: /var/log/pods/**/*.log
        relabel_configs:
          - target_label: job
            replacement: pod-logs
          - source_labels: ['__path__']
            target_label: 'filename'

      # ================================
      # 4️⃣ Spring Boot / Backend Logs (log dari app di /var/log/springboot)
      # ================================
      - job_name: springboot-logs
        static_configs:
          - targets:
              - localhost
            labels:
              job: springboot-logs
              host: ${HOSTNAME}
              __path__: /var/log/springboot/*.log
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: promtail
  namespace: monitoring
  labels:
    app: promtail
spec:
  selector:
    matchLabels:
      app: promtail
  template:
    metadata:
      labels:
        app: promtail
    spec:
      serviceAccountName: promtail
      containers:
        - name: promtail
          image: grafana/promtail:2.9.1
          args:
            - -config.file=/etc/promtail/promtail.yaml
          volumeMounts:
            - name: config
              mountPath: /etc/promtail
            - name: varlog
              mountPath: /var/log
              readOnly: true
            - name: pods
              mountPath: /var/log/pods
              readOnly: true
            - name: containers
              mountPath: /var/lib/containers
              readOnly: true
            - name: springboot-logs
              mountPath: /var/log/springboot
      volumes:
        - name: config
          configMap:
            name: promtail-config
        - name: varlog
          hostPath:
            path: /var/log
        - name: pods
          hostPath:
            path: /var/log/pods
        - name: containers
          hostPath:
            path: /var/lib/containers
        - name: springboot-logs
          hostPath:
            path: /var/log/springboot
